export const AppImages = {
    roundedImg: require('./logo.png'),
    step_one: require('./step_one.png'),
    step_two: require('./step_two.png'),
    step_three: require('./step_three.png'),
    header_shadow: require('./header_shadow.png'),
    user: require('./user.jpg'),
    first_banner_bg: require('./first_banner_bg.png'),
    second_banner_bg: require('./second_banner_bg.png'),
    header_bg: require('./header_bg.png'),
    bg: require('./bg.jpg'),
    services_profile_bg: require('./services_profile_bg.jpg'),
    animation: require('./animation.png'),
    dotsLeft: require('./dotsLeft.png'),
    dotsRight: require('./dotsRight.png'),
};